### ISSUE TITLE
Use patchwork to draft all figures and discuss formatting

### ISSUE THREAD

**Issue by kaitejohnson** [CDCgov/wastewater-informed-covid-forecasting#106]
## Goal
#84's goal is to produce code to generate all the subplots in the figures. This issue the goal is to use `patchwork` in R to format the ggplot objects for discussion among the team

## Requirements
- [ ] drafts of combined plots for manuscript

**Comment by damonbayer** [comment]
This can also [be done in cowplot](https://wilkelab.org/cowplot/articles/aligning_plots.html), which I also recommended for https://github.com/CDCgov/wastewater-informed-covid-forecasting/issues/109
