### ISSUE TITLE
Define a project wide ggplot theme `plotting_style.R`

### ISSUE THREAD

**Issue by kaitejohnson** [CDCgov/wastewater-informed-covid-forecasting#109]
## Goal
To avoid repeating them theme objects in each figure, define the style globally.

## Context
https://github.com/CDCgov/wastewater-informed-covid-forecasting/pull/105#discussion_r1684978579

**Comment by damonbayer** [comment]
Strong recommendation to base this off of something from [cowplot](https://wilkelab.org/cowplot/articles/themes.html), which incorporates many ideas from the author's book https://clauswilke.com/dataviz/
