### ISSUE TITLE
Move ordering functions to their own file and checks for column existence

### ISSUE THREAD

**Issue by kaitejohnson** [CDCgov/wastewater-informed-covid-forecasting#121]
Comment here, want them to be in a separate file
https://github.com/CDCgov/wastewater-informed-covid-forecasting/pull/112#discussion_r1696124673

**Comment by dylanhmorris** [comment]
Partially addressed by #123 but need to add the checks for the column to order existing. That can be a different PR.

**Comment by dylanhmorris** [comment]
@kaitejohnson

**Comment by kaitejohnson** [comment]
I can add it to this PR, I had added the check that the elements of the column existed but forgot to add the column existence!
