### ISSUE TITLE
Expanding compatible R versions

### ISSUE THREAD

**Issue by hannahcohen4** [CDCgov/wastewater-informed-covid-forecasting#154]
Currently `cfaforecastrenewalww` and `wweval` require `R >= 4.3.0`. Would it be possible to extend this to `R >= 4.1.0`?

**Comment by kaitejohnson** [comment]
This is also relevant to https://github.com/CDCgov/ww-inference-model as we also have this as a dependency.

I will test out on an older version of R tomorrow for both packages.
